# Generated by Django 5.2.16 on 2026-07-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vert_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionexecution',
            new_name='vert_helper_action__9b16bc_idx',
            old_name='vert_helper_action__f86d59_idx',
        ),
        migrations.RenameIndex(
            model_name='actionexecution',
            new_name='vert_helper_execute_fbe427_idx',
            old_name='vert_helper_executed_0f1579_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='vert_helper_action__7fcf33_idx',
            old_name='vert_helper_action__e62053_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='vert_helper_parent__94fbc5_idx',
            old_name='vert_helper_parent__c9808f_idx',
        ),
        migrations.RenameIndex(
            model_name='servicehealth',
            new_name='vert_helper_service_8b2115_idx',
            old_name='vert_helper_service_9d888f_idx',
        ),
        migrations.RenameIndex(
            model_name='servicehealth',
            new_name='vert_helper_status_75435b_idx',
            old_name='vert_helper_status_f98fe0_idx',
        ),
    ]
