# Generated by Django 5.2.16 on 2026-07-17 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vert_helper', '0002_rename_vert_helper_action__f86d59_idx_vert_helper_action__9b16bc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='action_kwarg',
            field=models.CharField(blank=True, help_text='Nome do argumento que será passado para a função da action.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_first',
            field=models.BooleanField(default=False, help_text='Indica se esta é a primeira pergunta da action.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, help_text='Pergunta pai que habilita esta pergunta quando respondida com parent_value.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vert_helper.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_value',
            field=models.CharField(blank=True, help_text='Valor da resposta da pergunta pai que habilita esta pergunta.', max_length=255, null=True),
        ),
    ]
